-- CREATING AND USING THAT DATABASE
CREATE DATABASE WORLD_BANK_API;
USE WORLD_BANK_API;


-- CREATE BRIDGE TABLE FOR MAKING CONNECTION WITH OTHER DIMESIONS AND FACT TABLES
CREATE TABLE BRIDGE_TABLE
(COUNTRY_ID VARCHAR(100) NOT NULL PRIMARY KEY);

ALTER TABLE [dbo].[economic]
DROP COLUMN  COUNTRY_VALUE, INDICATOR_NAME, YEAR, VALUE, REGION, INCOMELEVEL, 
            LENDINGTYPE, LONGITUDE , LATITUDE;

-- INSERTING THE UNIQUE COUNTRY ID VALUES IN TO BRIDGE TABLE 
INSERT INTO [dbo].[BRIDGE_TABLE]
SELECT DISTINCT ([COUNTRY_ID]) FROM [dbo].[ECONOMIC];


-- NOW DROPPING THE EXISTING ECONOMIC TABLE
DROP TABLE [dbo].[ECONOMIC];


--======================================== SCHEMA STRUCTURE =========================================

-- CREATE ECONOMIC TABLE, WITH COUNTRY ID AS FOREIGN KEY FROM BRRIDGE TABLE
CREATE TABLE [ECONOMIC]
(
	COUNTRY_ID VARCHAR(100),
	COUNTRY_VALUE VARCHAR(250),
	INDICATOR_NAME VARCHAR(250),
	YEAR INT,
	VALUE DECIMAL(12,3),
	REGION VARCHAR(400),
	INCOMELEVEL VARCHAR(250),
	LENDINGTYPE VARCHAR(250),
	LONGITUDE DECIMAL(12,3),
	LATITUDE  DECIMAL(12,3),

	CONSTRAINT FK_COUNTRY_ID_ECONOMIC 
	FOREIGN KEY (COUNTRY_ID) REFERENCES BRIDGE_TABLE([COUNTRY_ID])
);


-- CREATE ENVIROMENT TABLE, WITH COUNTRY ID AS FOREIGN KEY FROM BRRIDGE TABLE
CREATE TABLE [ENVIROMENT]
(
	COUNTRY_ID VARCHAR(100),
	COUNTRY_VALUE VARCHAR(400),
	INDICATOR_NAME VARCHAR(250),
	YEAR INT,
	VALUE FLOAT,
	REGION VARCHAR(250),
	INCOMELEVEL VARCHAR(250),
	LENDINGTYPE VARCHAR(250),
	LONGITUDE FLOAT,
	LATITUDE  FLOAT,

	CONSTRAINT FK_COUNTRY_ID_ENVIROMENT 
	FOREIGN KEY (COUNTRY_ID) REFERENCES BRIDGE_TABLE([COUNTRY_ID])
);


-- CREATE HEALTH TABLE, WITH COUNTRY ID AS FOREIGN KEY FROM BRRIDGE TABLE
CREATE TABLE [HEALTH]
(
	COUNTRY_ID VARCHAR(100),
	COUNTRY_VALUE VARCHAR(400),
	INDICATOR_NAME VARCHAR(250),
	YEAR INT,
	VALUE FLOAT,
	REGION VARCHAR(250),
	INCOMELEVEL VARCHAR(250),
	LENDINGTYPE VARCHAR(250),
	LONGITUDE FLOAT,
	LATITUDE  FLOAT,

	CONSTRAINT FK_COUNTRY_ID_HEALTH 
	FOREIGN KEY (COUNTRY_ID) REFERENCES BRIDGE_TABLE([COUNTRY_ID])
);


-- CREATE LABOUR MARKET TABLE, WITH COUNTRY ID AS FOREIGN KEY FROM BRRIDGE TABLE
CREATE TABLE [LABOUR_MARKET]
(
	COUNTRY_ID VARCHAR(100),
	COUNTRY_VALUE VARCHAR(400),
	INDICATOR_NAME VARCHAR(250),
	YEAR INT,
	VALUE FLOAT,
	REGION VARCHAR(250),
	INCOMELEVEL VARCHAR(250),
	LENDINGTYPE VARCHAR(250),
	LONGITUDE FLOAT,
	LATITUDE  FLOAT,

	CONSTRAINT FK_COUNTRY_ID_LABOUR_MARKET
	FOREIGN KEY (COUNTRY_ID) REFERENCES BRIDGE_TABLE([COUNTRY_ID])
);


-- CREATE POVERTY TABLE, WITH COUNTRY ID AS FOREIGN KEY FROM BRRIDGE TABLE
CREATE TABLE [POVERTY]
(
	COUNTRY_ID VARCHAR(100),
	COUNTRY_VALUE VARCHAR(400),
	INDICATOR_NAME VARCHAR(250),
	YEAR INT,
	VALUE FLOAT,
	REGION VARCHAR(250),
	INCOMELEVEL VARCHAR(250),
	LENDINGTYPE VARCHAR(250),
	LONGITUDE FLOAT,
	LATITUDE  FLOAT,

	CONSTRAINT FK_COUNTRY_ID_POVERTY
	FOREIGN KEY (COUNTRY_ID) REFERENCES BRIDGE_TABLE([COUNTRY_ID])
);


-- CREATE TECHNOLOGY TABLE, WITH COUNTRY ID AS FOREIGN KEY FROM BRRIDGE TABLE
CREATE TABLE [TECHNOLOGY]
(
	COUNTRY_ID VARCHAR(100),
	COUNTRY_VALUE VARCHAR(400),
	INDICATOR_NAME VARCHAR(250),
	YEAR INT,
	VALUE FLOAT,
	REGION VARCHAR(250),
	INCOMELEVEL VARCHAR(250),
	LENDINGTYPE VARCHAR(250),
	LONGITUDE FLOAT,
	LATITUDE  FLOAT,

	CONSTRAINT FK_COUNTRY_ID_TECHNOLOGY
	FOREIGN KEY (COUNTRY_ID) REFERENCES BRIDGE_TABLE([COUNTRY_ID])
);


-- CREATE TRADE TABLE, WITH COUNTRY ID AS FOREIGN KEY FROM BRRIDGE TABLE
CREATE TABLE [TRADE]
(
	COUNTRY_ID VARCHAR(100),
	COUNTRY_VALUE VARCHAR(400),
	INDICATOR_NAME VARCHAR(250),
	YEAR INT,
	VALUE FLOAT,
	REGION VARCHAR(250),
	INCOMELEVEL VARCHAR(250),
	LENDINGTYPE VARCHAR(250),
	LONGITUDE FLOAT,
	LATITUDE  FLOAT,

	CONSTRAINT FK_COUNTRY_ID_TRADE
	FOREIGN KEY (COUNTRY_ID) REFERENCES BRIDGE_TABLE([COUNTRY_ID])
);
GO;


DROP TABLE ECONOMIC, ENVIROMENT, TRADE, LABOUR_MARKET, HEALTH, POVERTY, TECHNOLOGY;
GO;


SELECT * FROM [dbo].[TRADE];
SELECT * FROM [dbo].[HEALTH];
SELECT * FROM [dbo].[POVERTY];
SELECT * FROM [dbo].[ECONOMIC];
SELECT * FROM [dbo].[TECHNOLOGY];
SELECT * FROM [dbo].[ENVIRONMENT];
SELECT * FROM [dbo].[LABOUR_MARKET];

--================================== BASIC MATRICS ==================================
-- 1. AVERAGE HEALTH SPENDING
SELECT ROUND(AVG(VALUE),2) AS AVG_SPENDING 
FROM [dbo].[HEALTH]
WHERE INDICATOR_NAME = 'CURRENT HEALTH EXPENDITURE (% OF GDP)';


-- 2. AREA UNDER THE FOREST
SELECT ROUND(AVG(VALUE),2) AS FOREST_AREA
FROM [dbo].[ENVIRONMENT]
WHERE INDICATOR_NAME = 'FOREST AREA (% OF LAND AREA)';


-- 3. AVERAGE GDP PER CAPITA
SELECT ROUND(AVG(VALUE),2) AS FOREST_AREA
FROM [dbo].[ECONOMIC]
WHERE INDICATOR_NAME = 'GDP GROWTH (ANNUAL %)';


-- 4. AVERAGE TRADE VALUE 
SELECT ROUND(AVG(VALUE),2) AS 'AVG TRADE'
FROM [dbo].[TRADE]


-- 5. AVERAGE GDP GROWTH
SELECT AVG(VALUE) AS 'AVG GDP GROWTH' FROM [dbo].[ECONOMIC]
WHERE INDICATOR_NAME = 'GDP GROWTH (ANNUAL %)';
GO;

-- 6. AVERAGE SPENDING ON HEALTH REGION WISE
SELECT REGION, ROUND(AVG(VALUE),2) AS AVG_SPENDING
FROM [dbo].[HEALTH]
WHERE REGION != 'AGGREGATES'
GROUP BY REGION
ORDER BY AVG_SPENDING DESC;

-- 7. BEST TOP 10 COUNTRIES IN POVERTY REDUCTION RATIO
SELECT TOP 10 COUNTRY_VALUE, ROUND(AVG(VALUE),2)  AS 'POVERTY REDUCTION RATIO'
FROM [dbo].[POVERTY]
WHERE INDICATOR_NAME = 'Poverty headcount ratio at national poverty lines (% of population)'
AND VALUE IS NOT NULL
GROUP BY COUNTRY_VALUE
ORDER BY 'POVERTY REDUCTION RATIO' DESC;


-- 8. WORST 10 COUNTRIES IN POVERTY REDUCTION RATIO
SELECT TOP 10 COUNTRY_VALUE, ROUND(AVG(VALUE),2)  AS 'POVERTY REDUCTION RATIO'
FROM [dbo].[POVERTY]
WHERE INDICATOR_NAME = 'Poverty headcount ratio at national poverty lines (% of population)'
AND VALUE IS NOT NULL
GROUP BY COUNTRY_VALUE
ORDER BY 'POVERTY REDUCTION RATIO' ASC;
